### ISSUE TITLE
undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by penguian** [ietf-ribose/tractive#107]
Hello,
I am currently using Tractive to see if I can migrate the CABLE Trac at https://trac.nci.org.au/trac/cable to Github by using a Conda environment that I have set up on gadi.nci.org.au. After apparently following all of the instructions up to https://github.com/ietf-ribose/tractive#running-tractive I now see:

```
(base) [pcl851@gadi-login-08 cable]$ tractive -M
[2023-09-14 14:49:56] INFO  | loading tickets
[2023-09-14 14:49:56] INFO  | created issue on GitHub is '0' 0
[2023-09-14 14:49:56] INFO  | loading revision map ./cable.revmap.txt
/g/data/tm70/pcl851/envs/trac/share/rubygems/gems/tractive-1.0.22/lib/tractive/migrator/engine.rb:66:in `initialize': undefined method `[]' for nil:NilClass (NoMethodError)

      @delete_mocked_tickets = args[:cfg]["ticket"]["delete_mocked"]
                                                   ^^^^^^^^^^^^^^^^^
        from /g/data/tm70/pcl851/envs/trac/share/rubygems/gems/tractive-1.0.22/lib/tractive/main.rb:38:in `new'
        from /g/data/tm70/pcl851/envs/trac/share/rubygems/gems/tractive-1.0.22/lib/tractive/main.rb:38:in `migrate'
        from /g/data/tm70/pcl851/envs/trac/share/rubygems/gems/tractive-1.0.22/lib/tractive/main.rb:33:in `run'
        from /g/data/tm70/pcl851/envs/trac/share/rubygems/gems/tractive-1.0.22/exe/tractive:53:in `migrate_tickets'
        from /g/data/tm70/pcl851/envs/trac/share/rubygems/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /g/data/tm70/pcl851/envs/trac/share/rubygems/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /g/data/tm70/pcl851/envs/trac/share/rubygems/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /g/data/tm70/pcl851/envs/trac/share/rubygems/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
        from /g/data/tm70/pcl851/envs/trac/share/rubygems/gems/tractive-1.0.22/exe/tractive:88:in `<top (required)>'
        from /g/data/tm70/pcl851/envs/trac/share/rubygems/bin/tractive:32:in `load'
        from /g/data/tm70/pcl851/envs/trac/share/rubygems/bin/tractive:32:in `<main>'
```
How do I diagnose this error and continue?

**Comment by ronaldtse** [comment]
Thank you @penguian for the report!

@HassanAkbar would you have time to look into this? Thanks!

**Comment by penguian** [comment]
Thanks. I have diagnosed this issue by comparing the error message to https://github.com/ietf-ribose/tractive/blob/main/README.adoc and the source code, noticing that I did not have 
```
ticket:
  delete_mocked: true
```
in `tractive.config.yaml`, adding this to the file and running `tractive` again. 

I am now working through similar messages such as:
```
(base) [pcl851@gadi-login-04 cable]$ tractive -v
[2023-09-15 15:05:48] INFO  | loading tickets
[2023-09-15 15:05:48] DEBUG | Get highest in penguian/cable
[2023-09-15 15:05:48] INFO  | created issue on GitHub is '0' 0
[2023-09-15 15:05:48] INFO  | loading revision map ./cable.revmap.txt
[2023-09-15 15:05:48] INFO  | migrating issues
[2023-09-15 15:05:49] INFO  | creating issue for trac 1 "zero difference tool re-instate diagnostics via cable_diag module (at least partially so)" (jxs599)
[2023-09-15 15:05:52] INFO  | loading revision map ./cable.revmap.txt
/g/data/tm70/pcl851/envs/trac/share/rubygems/gems/tractive-1.0.22/lib/tractive/migrator/converter/trac_to_github.rb:179:in `compose': undefined method `[]' for nil:NilClass (NoMethodError)

          github_owner = @users[owner]["username"]
                                      ^^^^^^^^^^^^
	from /g/data/tm70/pcl851/envs/trac/share/rubygems/gems/tractive-1.0.22/lib/tractive/migrator/engine/migrate_from_db.rb:57:in `block in migrate_tickets_from_db'
...
```
by comparing the `users:` section in `tractive.config.yaml` with the Trac tickets at https://trac.nci.org.au/trac/cable and fixing them one at a time. Right now, since I am testing the porting process, I have set all of the GitHub usernames to my own username `penguian`. Later, when we (ACCESS-NRI) do the real porting, we will need to determine what GitHub usernames to use for people who are not on GitHub or who have left the porject. If I get stuck with the `users:` section, I will create a separate issue.
